"use server";

import { logger } from "@/lib/logger";
import { supabase } from "@/lib/supabase";
import { revalidatePath } from "next/cache";

/**
 * Updates alert product context.
 * Saves raw text only - AI summarization is handled by Worker 2.
 */
export async function updateAlertProductContext(formData: FormData) {
  const alertId = String(formData.get("alertId") || "").trim();
  const rawDescription = String(formData.get("rawDescription") || "");

  if (!alertId) {
    logger.error(
      "DB_UPDATE_ERROR",
      "Missing alertId in updateAlertProductContext",
      {}
    );
    return;
  }

  logger.info(
    "DB_UPDATE",
    "Updating alert product context",
    {
      alertId,
      descriptionLength: rawDescription.length,
      columns: ["product_description_raw"],
    }
  );

  // Note: product_context will be generated by Worker 2 based on product_description_raw
  // We only save the raw description here
  const { error } = await supabase
    .from("alerts")
    .update({
      product_description_raw: rawDescription,
      // product_context will be set by Worker 2 when it processes the raw description
    })
    .eq("id", alertId);

  if (error) {
    logger.error(
      "DB_UPDATE_ERROR",
      "Failed to update alert product context",
      {
        alertId,
        message: error.message,
        code: (error as any).code,
      }
    );
    return;
  }

  logger.info(
    "DB_UPDATE",
    "Alert product context updated",
    {
      alertId,
      descriptionLength: rawDescription.length,
    }
  );

  // Ensure dashboard reflects latest data
  revalidatePath("/dashboard");
}

